### PR TITLE
adding new workflow that tests develop branch of dependent libraries

### LINKED ISSUE #91: add CI workflow that tests against develop branch of dependent NCEPLIBS libraries
grib_util depends on:
* sp
* ip
* w3nco
* g2
* bacio

We need to test against the develop branch of each of these projects. THat way, if we break something by changing those projects, we will find it sooner...

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #91 

adding new workflow that tests develop branch of dependent libraries

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@kgerheiser should grib_utils build with the current develop branch of ip?

It is failing to find a function. Is that because of the merge with ip2?

```
/usr/bin/ld: CMakeFiles/copygb.dir/copygb.F.o: in function `intgrib1_':
/home/runner/work/NCEPLIBS-grib_util/NCEPLIBS-grib_util/grib_utils/src/copygb/copygb.F:1222: undefined reference to `ipolates_'


```

**Comment by kgerheiser** [comment]
That's exactly what it is. You can use v3.3.3, or add `use ip_mod` for develop.

**Comment by edwardhartnett** [comment]
OK, so every NCEPLIBS library (and other user) that uses ip needs to change their build system to cope with this. ;-)

**Comment by kgerheiser** [comment]
Not the build system, but the actual code.

**Comment by edwardhartnett** [comment]
Right, but the build system also, because that use statement can't be used with older versions of ip.

So either the build system demands version 3.4.0 or greater, or uses a pre-processor flag and some ifdef magic to include the use statement only if version >= 3.4.0.

When are we going to release ip-3.4.0? Seems like we need to, so that grib_util and other utilities can test against the new way of doing ip.

**Comment by edwardhartnett** [comment]
OK, the ip problem still needs to be resolved, so I change ip to 3.3.0 in the CI. This PR is ready to merge.

**Review by kgerheiser — APPROVED** [review]

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Pull request merged**
