### PR TITLE
now each utility gets its own documentation

### LINKED ISSUE #78: add doxygen for each of the utilities
We faced a similar situation in UFS_UTILS: a bunch of programs that had nothing to do with each other. Making this look good in the documentation is impossible, since it lists the functions etc. from each utility, all in one big jumbled list.

What we ended up doing is a separate doxygen build for each utility. So each utility gets a docs directory, and in it a Doxygen.in file and user_guide.md.

Then the top-level documentation build just has a one-page description of the utilities, with a link to their docs.

This is a pain to set up but, once done, every utility gets nice documentation, and it's easy to maintain because we rarely change the doxyfile.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #78 

Now each utility gets its own doxygen build.

What this means is that each subdirectory under src now gets a docs subdirectory, and those docs directories each contain a CMakeLists.txt, user_guide.md, and Doxyfile.in.

The top-level doxygen build is just one page, which lists the utilities and links to their docs.

### CODE REVIEW

**Comment by Hang-Lei-NOAA** [comment]
This change added Doxyfiles into each level. Is better to do this way or have a top level and then just adding doxygen into the src code of sub-level?  Would the differences or changes in the individual doxyfiles in sub directories become hard to manage?

**Comment by edwardhartnett** [comment]
It is a pain but this seems the best solution. We did this for UFS_UTILS and its working well. grib_utils and UFS_UTILS are the same, a bunch of utilities that have little to do with each other.

So when looking a the documentation of grib2grib, it would be confusing to see all the functions and files from all the other utilities as well.

In practice, the Doxyfile changes rarely.

**Review by Hang-Lei-NOAA — APPROVED** [review]
Overall it is very good. Further tiny format issues can be updated later.

**Comment by edwardhartnett** [comment]
Yes, many formatting updates are needed! Feel free to jump in and do some. ;-)

One thing our experience has taught me is that documentation has to be in place before testing can happen. It's practically impossible to test without some documentation, and fortunately we have good legacy documentation here. By converting to doxygen early, and updating and improving it during the testing work, we will end up with good docs and good tests. ;-)

**Pull request merged**
