### PR TITLE
Add copygb test for NCEP grids 172 and 220.

### LINKED ISSUE #202: New copygb tests for NCEP grids 172 and 220
copygb does not work for pre-defined NCEP grids 172 and 220. This is due to a problem in the w3emc library (see this issue: https://github.com/NOAA-EMC/NCEPLIBS-w3emc/issues/157). 

Add a copygb unit test for these grids.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Test interpolates GFS land mask data to grids 172 and 220 and compares the output to baseline files.

Note: this test depends on a bug fix in the w3emc library. See: https://github.com/NOAA-EMC/NCEPLIBS-w3emc/pull/158

Part of #202.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, I think what we want to do here is release a new version of w3emc, and then enforce that that is the version found by grib_util.

I will do this...

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can you merge develop into this branch? I have fixed the MacOS problem in the CI, so it should work now.

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett The new copygb tests require a new w3emc release. The workflows that use the head of 'develop' are passing. Those that use release 2.9.3 or earlier are failing.

**Comment by edwardhartnett** [comment]
OK, this has been open forever!

@GeorgeGayno-NOAA if you can comment out the new tests in your cmake file we can merge this and I can submit another PR that turns on these tests when we are using the correct versions of w3emc.

**Review by edwardhartnett — APPROVED** [review]
I will do a follow-up PR to turn these tests on when appropriate.

**Pull request merged**
